import pygame
from cccc import *
BLACK_pawn = pygame.image.load("images/black pawn.png")
WHITE_pawn = pygame.image.load("images/white pawn.png")
BLACK_rook = pygame.image.load("images/black rook.png")
WHITE_rook = pygame.image.load("images/white rook.png")
BLACK_knight = pygame.image.load("images/black knight.png")
WHITE_knight = pygame.image.load("images/white knight.png")
BLACK_bishop = pygame.image.load("images/black bishop.png")
WHITE_bishop = pygame.image.load("images/white bishop.png")
BLACK_queen = pygame.image.load("images/black queen.png")
WHITE_queen = pygame.image.load("images/white queen.png")
BLACK_king = pygame.image.load("images/black king.png")
WHITE_king = pygame.image.load("images/white king.png")



BLACK_pawn = pygame.transform.scale(BLACK_pawn, (55, 55))
WHITE_pawn = pygame.transform.scale(WHITE_pawn, (55,55))
BLACK_rook = pygame.transform.scale(BLACK_rook, (55,55))
WHITE_rook = pygame.transform.scale(WHITE_rook, (55,55))
BLACK_knight = pygame.transform.scale(BLACK_knight, (55,55))
WHITE_knight = pygame.transform.scale(WHITE_knight, (55,55))
BLACK_bishop = pygame.transform.scale(BLACK_bishop, (55,55))
WHITE_bishop = pygame.transform.scale(WHITE_bishop, (55,55))
BLACK_queen = pygame.transform.scale(BLACK_queen, (55,55))
WHITE_queen = pygame.transform.scale(WHITE_queen, (55,55))
BLACK_king = pygame.transform.scale(BLACK_king, (55,55))
WHITE_king = pygame.transform.scale(WHITE_king, (55,55))



W_knight1 = WTknight1(WHITE_knight)
B_knight1 = BKknight1(BLACK_knight)
W_knight2 = WTknight2(WHITE_knight)
B_knight2 = BKknight2(BLACK_knight)
W_rook1 = WTrook1(WHITE_rook)
W_rook2 = WTrook2(WHITE_rook)
B_rook1 = BKrook1(BLACK_rook)
B_rook2 = BKrook2(BLACK_rook)
W_bishop1 = WTbishop1(WHITE_bishop)
W_bishop2 = WTbishop2(WHITE_bishop)
B_bishop1 = BKbishop1(BLACK_bishop)
B_bishop2 = BKbishop2(BLACK_bishop)
W_queen = WTqueen(WHITE_queen)
B_queen = BKqueen(BLACK_queen)
W_king = WTking(WHITE_king)
B_king = BKking(BLACK_king)

W_pawn1 = WTpawn1(WHITE_pawn)
W_pawn2 = WTpawn2(WHITE_pawn)
W_pawn3 = WTpawn3(WHITE_pawn)
W_pawn4 = WTpawn4(WHITE_pawn)
W_pawn5 = WTpawn5(WHITE_pawn)
W_pawn6 = WTpawn6(WHITE_pawn)
W_pawn7 = WTpawn7(WHITE_pawn)
W_pawn8 = WTpawn8(WHITE_pawn)

B_pawn1 = BKpawn1(BLACK_pawn)
B_pawn2 = BKpawn2(BLACK_pawn)
B_pawn3 = BKpawn3(BLACK_pawn)
B_pawn4 = BKpawn4(BLACK_pawn)
B_pawn5 = BKpawn5(BLACK_pawn)
B_pawn6 = BKpawn6(BLACK_pawn)
B_pawn7 = BKpawn7(BLACK_pawn)
B_pawn8 = BKpawn8(BLACK_pawn)
